# Generated by Django 5.2.8 on 2025-11-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BIRYANI', 'Biryani'), ('BURGER', 'Burger'), ('DESSERT', 'Dessert'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
