# Generated by Django 5.2.8 on 2025-11-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_menuitem_food_type_menuitem_is_veg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(blank=True, help_text='Pizza, Biryani, Pasta, Burger, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
